# Generated by Django 5.2.4 on 2025-07-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE appointments_userprofile 
            ADD COLUMN IF NOT EXISTS experience_years integer DEFAULT 0,
            ADD COLUMN IF NOT EXISTS rating numeric(3,2) DEFAULT 4.50,
            ADD COLUMN IF NOT EXISTS consultation_fee numeric(8,2) DEFAULT 0.00,
            ADD COLUMN IF NOT EXISTS bio text,
            ADD COLUMN IF NOT EXISTS languages jsonb DEFAULT '[]',
            ADD COLUMN IF NOT EXISTS certifications jsonb DEFAULT '[]',
            ADD COLUMN IF NOT EXISTS next_available timestamp with time zone,
            ADD COLUMN IF NOT EXISTS total_appointments integer DEFAULT 0;
            """,
            reverse_sql="""
            ALTER TABLE appointments_userprofile 
            DROP COLUMN IF EXISTS experience_years,
            DROP COLUMN IF EXISTS rating,
            DROP COLUMN IF EXISTS consultation_fee,
            DROP COLUMN IF EXISTS bio,
            DROP COLUMN IF EXISTS languages,
            DROP COLUMN IF EXISTS certifications,
            DROP COLUMN IF EXISTS next_available,
            DROP COLUMN IF EXISTS total_appointments;
            """
        ),
    ]
