# Generated by Django 4.2.11 on 2025-07-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_organization_admin_alter_organization_org_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
    ]
